### ISSUE TITLE
Add feature to ignore URL Pattern

### ISSUE THREAD

**Issue by badalsarkar** [danishalim/URLChecker#7]
Hi @danishalim ,
I would like to implement a new feature which will allow user to specify certain URLs to be ignored by the application. I will add a new option `--ignore`/`-i`. Please let me know if its alright.

Thanks.

**Comment by badalsarkar** [comment]
Actually I am getting the following error

```bash
urlcheck -f urls.html -s
(node:492113) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of null
    at fetch (/home/badal/Documents/codeProject/URLChecker/index.js:40:11)
    at /home/badal/Documents/codeProject/URLChecker/index.js:70:3

(node:492113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:492113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
